"""
QUICK START GUIDE
=================

Follow these steps to get your Advanced Phishing Detection System up and running!

"""

print("=" * 80)
print("🚀 ADVANCED PHISHING DETECTION SYSTEM - QUICK START GUIDE")
print("=" * 80)
print()

print("📋 STEP-BY-STEP INSTRUCTIONS:")
print()

print("STEP 1: Activate Virtual Environment")
print("-" * 40)
print("Run this command:")
print("   .venv\\Scripts\\activate")
print()

print("STEP 2: Install Dependencies")
print("-" * 40)
print("Run this command:")
print("   pip install -r requirements.txt")
print()
print("This will install:")
print("   ✓ scikit-learn, pandas, numpy, xgboost")
print("   ✓ streamlit, plotly, matplotlib, seaborn")
print("   ✓ tldextract, dnspython")
print("   ✓ and more...")
print()

print("STEP 3: Train the Model")
print("-" * 40)
print("Run this command:")
print("   python train_model_advanced.py")
print()
print("This will:")
print("   ✓ Load 30,000+ URLs from the dataset")
print("   ✓ Train an ensemble model (RF + GB + XGB)")
print("   ✓ Achieve 95%+ accuracy")
print("   ✓ Save model files (phishing_model.pkl, scaler.pkl, etc.)")
print("   ✓ Create performance visualizations")
print()
print("⏱️ Training time: ~2-5 minutes (depending on your CPU)")
print()

print("STEP 4: Run the Streamlit App")
print("-" * 40)
print("Run this command:")
print("   streamlit run streamlit_app.py")
print()
print("This will:")
print("   ✓ Launch the web interface at http://localhost:8501")
print("   ✓ Open automatically in your default browser")
print()

print("STEP 5: Test URLs")
print("-" * 40)
print("Try these examples in the app:")
print()
print("SAFE URLs:")
print("   • https://www.google.com")
print("   • https://www.github.com")
print("   • https://www.microsoft.com")
print()
print("PHISHING URLs:")
print("   • http://g00gle-login.com")
print("   • http://paypal-verify.tk")
print("   • http://secure-account-update.xyz")
print()

print("=" * 80)
print("📊 EXPECTED MODEL PERFORMANCE:")
print("=" * 80)
print("   Accuracy:  95-98%")
print("   Precision: 95-97%")
print("   Recall:    94-96%")
print("   F1-Score:  95-97%")
print("   ROC-AUC:   98-99%")
print()

print("=" * 80)
print("🎯 PROJECT FEATURES:")
print("=" * 80)
print("   ✅ Ensemble ML Model (3 algorithms)")
print("   ✅ 30,000+ training samples")
print("   ✅ Beautiful Streamlit UI")
print("   ✅ Real-time phishing detection")
print("   ✅ Interactive visualizations")
print("   ✅ Detailed feature analysis")
print("   ✅ Gauge charts, pie charts, bar charts")
print()

print("=" * 80)
print("🛠️ TROUBLESHOOTING:")
print("=" * 80)
print()
print("Problem: 'Model files not found'")
print("Solution: Run 'python train_model_advanced.py' first")
print()
print("Problem: 'Module not found'")
print("Solution: Run 'pip install -r requirements.txt'")
print()
print("Problem: 'Dataset not found'")
print("Solution: Ensure 'PhiUSIIL_Phishing_URL_Dataset.csv' is in the project folder")
print()

print("=" * 80)
print("📁 FILES CREATED AFTER TRAINING:")
print("=" * 80)
print("   • phishing_model.pkl         - Trained model")
print("   • scaler.pkl                 - Feature scaler")
print("   • feature_names.pkl          - Feature mapping")
print("   • model_metrics.pkl          - Performance metrics")
print("   • feature_importance.csv     - Feature rankings")
print("   • model_performance.png      - Visualization")
print()

print("=" * 80)
print("✨ READY TO START!")
print("=" * 80)
print()
print("Quick commands:")
print("   1. .venv\\Scripts\\activate")
print("   2. pip install -r requirements.txt")
print("   3. python train_model_advanced.py")
print("   4. streamlit run streamlit_app.py")
print()
print("🔒 Stay safe online!")
print("=" * 80)
